### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by chrispahm** [sl-nx/superlogin-next#1]
Hey @LyteFM 

Just wanted to say thank you for providing this maintained fork of superlogin! I still love using PouchDB/CouchDB and was running into issues when upgrading to CouchDB v3. However, your fork solved all my issues, so once again, thank you!

Best
Christoph

**Comment by LyteFM** [comment]
Glad to hear! I'm still actively developing this fork and it's not 1.0.0 yet, so better pin your commit hashes. I've released a [first renamed version on NPM](https://www.npmjs.com/package/@sl-nx/superlogin-next).
