### ISSUE TITLE
Add 'forgot-username' route and functionality

### ISSUE THREAD

**Issue by rilrom** [sl-nx/superlogin-next#4]
The users email address would be sent with the body and if that email address exists it would be sent an email with the username.
Currently if the user forgets their username there would be no way for them to ever gain access to their account.

Thanks for this brilliant updated fork of SuperLogin @LyteFM.

**Comment by LyteFM** [comment]
Yeah at the moment you can only use the `forgot-password` route for that purpose. You have the `user` - context in the Template so you can also send the username in the password reset email.
Feel free to submit a PR if you need a separate route for that - it would be the same as in `user.forgotPassword` but without the token generation.

**Comment by rilrom** [comment]
I'll put together a PR soon to remove the ambiguity for future users that decide to use the current version.
Looking forward to testing out the new version.
